### ISSUE TITLE
memcpy intrinsic tests failing on ARM64 with LLVM-13

### ISSUE THREAD

**Issue by ekilmer** [lifting-bits/rellic#233]
I am seeing the following errors with rellic using LLVM-13 on ARM64 machine (from cxx-common run here https://github.com/lifting-bits/cxx-common/runs/5254913519?check_suite_focus=true#step:15:171)

```
FAIL: test_byval_struct (__main__.TestRoundtrip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../scripts/roundtrip.py", line 120, in test
    roundtrip(self, args.rellic, path, args.clang, args.timeout, args.translate_only)
  File "../scripts/roundtrip.py", line 92, in roundtrip
    compile(self, clang, rt_c, out2, timeout, ["-Wno-everything"])
  File "../scripts/roundtrip.py", line 44, in compile
    self.assertEqual(
AssertionError: 204 != 0 : errors or warnings during compilation: /usr/bin/ld: /tmp/rt-0482d1.o: in function `main':
rt.c:(.text+0xbc): undefined reference to `llvm_memcpy_p0i8_p0i8_i64'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)


======================================================================
FAIL: test_issue_183_literal_structs (__main__.TestRoundtrip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../scripts/roundtrip.py", line 120, in test
    roundtrip(self, args.rellic, path, args.clang, args.timeout, args.translate_only)
  File "../scripts/roundtrip.py", line 81, in roundtrip
    decompile(self, rellic, rt_bc, rt_c, timeout)
  File "../scripts/roundtrip.py", line 59, in decompile
    self.assertEqual(p.returncode, 0, "rellic-decomp failure: %s" % p.stderr)
AssertionError: -6 != 0 : rellic-decomp failure: error: array type 'unsigned long [2]' is not assignable
F0219 03:17:10.542593 25774 ASTBuilder.cpp:355] Check failed: er.isUsable() 
```

@pgoodman says "we should be lifting those intrinsics to calls to memcpy"

**Comment by frabert** [comment]
This may seem like a garbage proposal but... What if we linked the programs against a library containing implementations of those intrinsics?

**Comment by pgoodman** [comment]
I'd prefer to try to generate declarations that are closer to what's either available via `__builtin_*` intrinsics at the C level or using libc functions that will roundtrip to the same thing, e.g. `memcpy`, `memcmp`, etc.

**Comment by pgoodman** [comment]
That is, I want to avoid introducing functions that never existed in the first place.
