### ISSUE TITLE
Test Failure on Mac with Z3

### ISSUE THREAD

**Issue by ekilmer** [lifting-bits/rellic#79]
There is a failure that appears only on MacOS, as discovered in #78 

The error is below and appears on LLVM versions 9, 10, 11, with Z3 version `4.8.9`

```
Running tests...
/usr/local/Cellar/cmake/3.19.1/bin/ctest --force-new-ctest-process 
Test project /Users/runner/work/rellic/rellic/rellic-build
    Start 1: test_roundtrip
1/1 Test #1: test_roundtrip ...................***Failed    9.33 sec
.F.................
======================================================================
FAIL: test_assert (__main__.TestRoundtrip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/rellic/rellic/scripts/roundtrip.py", line 112, in test
    roundtrip(self, args.rellic, path, args.clang, args.timeout)
  File "/Users/runner/work/rellic/rellic/scripts/roundtrip.py", line 78, in roundtrip
    decompile(self, rellic, rt_bc, rt_c, timeout)
  File "/Users/runner/work/rellic/rellic/scripts/roundtrip.py", line 59, in decompile
    self.assertEqual(p.returncode, 0, "rellic-decomp failure: %s" % p.stderr)
AssertionError: -6 != 0 : rellic-decomp failure: F1211 15:53:30.115931 156609984 Z3ConvVisitor.cpp:65] Check failed: expr.is_bv() z3::expr is not a bitvector!
*** Check failure stack trace: ***
    @        0x1016d323f  google::LogMessageFatal::~LogMessageFatal()
    @        0x1016cf7e9  google::LogMessageFatal::~LogMessageFatal()


----------------------------------------------------------------------
Ran 19 tests in 8.666s

FAILED (failures=1)
```

**Comment by surovic** [comment]
Resolved via #78
