### ISSUE TITLE
The condition inside if statement could not be a function

### ISSUE THREAD

**Issue by Muqi-Zou** [lifting-bits/rellic#94]
When I trying to decompile the bc file generated by following code 
```
#include <stdio.h>
#include <string.h>


int main () {
   char str1[20];
   char str2[20];
   int result;

   //Assigning the value to the string str1
   strcpy(str1, "hello");

   //Assigning the value to the string str2
   strcpy(str2, "helLO WORLD");

   //This will compare the first 3 characters
   if(strncmp(str1, str2, 3) > 0) {
      printf("ASCII value of first unmatched character of str1 is greater than str2");
   } else if(result < 0) {
      printf("ASCII value of first unmatched character of str1 is less than str2");
   } else {
      printf("Both the strings str1 and str2 are equal");
   }

   return 0;
}
```
with 
```
$ clang -emit-llvm -c xxx -o xxx.bc
$ ./rellic-build/tools/rellic-decomp-10.0 --input xxx.bc --output xxx_generated.c
```
I received following error:
```
F0215 16:30:39.637413 27356 Z3ConvVisitor.cpp:324] Unimplemented FunctionDecl visitor11
*** Check failure stack trace: ***
    @     0x556a801557ac  google::LogMessageFatal::~LogMessageFatal()
    @     0x556a7ed39368  rellic::Z3ConvVisitor::VisitFunctionDecl()
Aborted (core dumped
```
I add more logs in "bool Z3ConvVisitor::VisitFunctionDecl(clang::FunctionDecl *func) " at "rellic/AST/Z3ConvVisitor.cpp" as following:
```
bool Z3ConvVisitor::VisitFunctionDecl(clang::FunctionDecl *func) {
  //https://clang.llvm.org/doxygen/structclang_1_1DeclarationNameInfo.html
  LOG(INFO) << "Name of function is : "<<func->getNameInfo().getName().getAsString();
  LOG(INFO) << "Declare Info is " << func->getNameInfo().getAsString();
  DLOG(INFO) << "VisitFunctionDecl";
  LOG(FATAL) << "Unimplemented FunctionDecl visitor11";
  return true;
}
```
And it told me that the function blocks at strncmp:
```
I0215 16:10:10.213157 25450 Z3ConvVisitor.cpp:320] Name of function is : strncmp
I0215 16:10:10.213160 25450 Z3ConvVisitor.cpp:321] Declare Info is strncmp
F0215 16:10:10.213161 25450 Z3ConvVisitor.cpp:324] Unimplemented FunctionDecl visitor11
```
Meanwhile, extract "strncmp" out of "if statement" makes everything works.

I tried to fix this but not sure where to start, is this a bug or any reason we do not want to fix this?

For the gdb info, it is here:
```
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6ec4921 in __GI_abort () at abort.c:79
#2  0x00005555572569fd in google::DumpStackTraceAndExit() ()
#3  0x000055555724eedc in google::LogMessage::SendToLog() ()
#4  0x000055555724f4ce in google::LogMessage::Flush() ()
#5  0x00005555572527ac in google::LogMessageFatal::~LogMessageFatal() ()
#6  0x0000555555e36368 in rellic::Z3ConvVisitor::VisitFunctionDecl (this=<optimized out>, 
    func=0x555558d327c0) at /home/muqi/decompile_tool/rellic/rellic/AST/Z3ConvVisitor.cpp:324
#7  0x0000555555e3ef8b in clang::RecursiveASTVisitor<rellic::Z3ConvVisitor>::WalkUpFromFunctionDecl (D=0x555558d327c0, this=<optimized out>)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/DeclNodes.inc:401
#8  rellic::Z3ConvVisitor::TraverseFunctionDecl (func=0x555558d327c0, this=<optimized out>)
    at /home/muqi/decompile_tool/rellic/rellic/AST/Z3ConvVisitor.h:91
#9  clang::RecursiveASTVisitor<rellic::Z3ConvVisitor>::TraverseDecl (this=0x555558d3a000, 
    D=0x555558d327c0)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/DeclNodes.inc:401
#10 0x0000555555e3a30b in rellic::Z3ConvVisitor::GetOrCreateZ3Decl (
    this=this@entry=0x555558d3a000, c_decl=c_decl@entry=0x555558d327c0)
    at /home/muqi/decompile_tool/rellic/rellic/AST/Z3ConvVisitor.cpp:262
#11 0x0000555555e3a40f in rellic::Z3ConvVisitor::VisitDeclRefExpr (this=0x555558d3a000, 
    c_ref=0x555558d32f68)
    at /home/muqi/decompile_tool/rellic/rellic/AST/Z3ConvVisitor.cpp:672
#12 0x0000555555e3a51c in clang::RecursiveASTVisitor<rellic::Z3ConvVisitor>::TraverseStmt (
    this=this@entry=0x555558d3a000, S=S@entry=0x555558d332e0, Queue=0x0)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/RecursiveASTVisitor.h:653
#13 0x0000555555e3a6bb in rellic::Z3ConvVisitor::GetOrCreateZ3Expr (this=0x555558d3a000, 
    c_expr=c_expr@entry=0x555558d332e0)
    at /home/muqi/decompile_tool/rellic/rellic/AST/Z3ConvVisitor.cpp:254
#14 0x0000555555e09dc3 in rellic::Z3CondSimplify::SimplifyCExpr (
    this=this@entry=0x555558d370b0, c_expr=0x555558d332e0)
    at /home/muqi/decompile_tool/rellic/rellic/AST/Z3CondSimplify.cpp:44
#15 0x0000555555e0a320 in rellic::Z3CondSimplify::VisitIfStmt (
    this=this@entry=0x555558d370b0, stmt=0x555558d33600)
    at /home/muqi/decompile_tool/rellic/rellic/AST/Z3CondSimplify.cpp:56
#16 0x0000555555e0ad99 in clang::RecursiveASTVisitor<rellic::Z3CondSimplify>::WalkUpFromIfStmt (S=<optimized out>, this=0x555558d370d0)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/StmtNodes.inc:121
#17 clang::RecursiveASTVisitor<rellic::Z3CondSimplify>::PostVisitStmt (
    this=this@entry=0x555558d370d0, S=<optimized out>)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/StmtNodes.inc:121
#18 0x0000555555e0a608 in clang::RecursiveASTVisitor<rellic::Z3CondSimplify>::TraverseStmt (
    this=this@entry=0x555558d370d0, S=<optimized out>, Queue=0x0)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/RecursiveASTVisitor.h:653
#19 0x0000555555e323d0 in clang::RecursiveASTVisitor<rellic::Z3CondSimplify>::TraverseFunctionHelper (this=this@entry=0x555558d370d0, D=D@entry=0x555558d39660)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/RecursiveASTVisitor.h:2072
---Type <return> to continue, or q <return> to quit---
#20 0x0000555555e32557 in clang::RecursiveASTVisitor<rellic::Z3CondSimplify>::TraverseFunctionDecl (this=0x555558d370d0, D=0x555558d39660)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/RecursiveASTVisitor.h:2077
#21 0x0000555555e0a554 in clang::RecursiveASTVisitor<rellic::Z3CondSimplify>::TraverseDeclContextHelper (this=this@entry=0x555558d370d0, DC=DC@entry=0x555558d29c00)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/RecursiveASTVisitor.h:1410
#22 0x0000555555e223aa in clang::RecursiveASTVisitor<rellic::Z3CondSimplify>::TraverseDeclContextHelper (DC=<optimized out>, this=0x555558d370d0)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/Decl.h:105
#23 clang::RecursiveASTVisitor<rellic::Z3CondSimplify>::TraverseTranslationUnitDecl (
    this=0x555558d370d0, D=0x555558d29bd8)
    at /home/muqi/decompile_tool/lifting-bits-downloads/vcpkg_ubuntu-18.04_llvm-10_amd64/installed/x64-linux-rel/include/clang/AST/RecursiveASTVisitor.h:1511
#24 0x0000555555e0a4c1 in rellic::Z3CondSimplify::runOnModule (this=0x555558d370b0, 
    module=...) at /home/muqi/decompile_tool/rellic/rellic/AST/Z3CondSimplify.cpp:73
#25 0x0000555555f525a8 in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
#26 0x0000555555ccf1e3 in (anonymous namespace)::GeneratePseudocode (output=..., module=..., 
    this=<optimized out>) at /home/muqi/decompile_tool/rellic/tools/decomp/Decomp.cpp:95
#27 main (argc=<optimized out>, argv=<optimized out>)
    at /home/muqi/decompile_tool/rellic/tools/decomp/Decomp.cpp:202
```

**Comment by tly000** [comment]
i tried to implement the feature, but its still broken for some unknown reason... this is my try:

https://github.com/tly000/rellic/commit/f05a37239c1c0b301899c635a7270e4eed4e5084

im not quite sure if the tool crashes because of my changes or because of another problem:
```
I0509 17:24:50.739872  7999 Z3ConvVisitor.cpp:881] VisitConstant: k!0
F0509 17:24:50.739933  7999 Z3ConvVisitor.cpp:183] Check failed: c_decl_map.count(id) No C equivalent for Z3 declaration!
*** Check failure stack trace: ***
    @     0x55d700b6bd3c  google::LogMessageFatal::~LogMessageFatal()
    @     0x55d6ff478ef6  rellic::Z3ConvVisitor::GetCValDecl()

```

**Comment by tly000** [comment]
yes, but my changes seem to work on a very simple example, the error is most likely unrelated. if youre interested, i ported the changes to the other branch:

https://github.com/tly000/rellic/commit/4e27a73c3e018bfbb6b4635639216e824f38eaf8
